version: "3"

services:
  client-api:
    build: dock-client-api/.
    depends_on:
      - mongo-db
    ports:
      - "3000:3000"
    volumes:
      - ./dock-client-api:/usr/app
    environment:
      DOCK_CLIENT_DB_URL: mongodb://mongo-db:27017/client-api?retryWrites=true&w=majority
  
  account-api:
    build: dock-account-api/.
    depends_on:
      - mongo-db
    ports:
      - "3001:3001"
    volumes:
      - ./dock-account-api:/usr/app
    environment:
      DOCK_CLIENT_API_URL: http://client-api:3000
      DOCK_ACCOUNT_DB_URL: mongodb://mongo-db:27017/account-api?retryWrites=true&w=majority
      
  mongo-db:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo-db:27017/