version: "3"

services:
  banking-api-gateway:
    build: banking-api-gateway/.
    ports:
      - "3000:3000"
    depends_on:
      - client-api
      - account-api
      - transaction-api
    # volumes:
    #   - ./banking-api-gateway:/usr/app
    environment:
      BASE_URL: /docs
      SWAGGER_JSON: /usr/app/swagger-output.json
  
  client-api:
    build: client-api/.
    depends_on:
      - mongo-db
    ports:
      - "3001:3001"
    # volumes:
    #   - ./client-api:/usr/app
    environment:
      CLIENT_DB_URL: mongodb://mongo-db:27017/client-api?retryWrites=true&w=majority
  
  account-api:
    build: account-api/.
    depends_on:
      - mongo-db
    ports:
      - "3002:3002"
    # volumes:
    #   - ./account-api:/usr/app
    environment:
      CLIENT_API_URL: http://client-api:3001
      TRANSACTION_API_URL: http://transaction-api:3003
      ACCOUNT_DB_URL: mongodb://mongo-db:27017/account-api?retryWrites=true&w=majority
  
  transaction-api:
    build: transaction-api/.
    depends_on:
      - mongo-db
    ports:
      - "3003:3003"
    # volumes:
      # - ./transaction-api:/usr/app
    environment:
      ACCOUNT_API_URL: http://account-api:3002/account/
      CLIENT_API_URL: http://client-api:3001/person/
      TRANSACTION_DB_URL: mongodb://mongo-db:27017/transaction-api?retryWrites=true&w=majority
      
  mongo-db:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    profiles:
      - debug
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo-db:27017/
    